### ISSUE TITLE
`json` is a built-in library

### ISSUE THREAD

**Issue by devlocalhost** [jaruizra/Geekbench5-data-analysis-tool#1]
At https://github.com/jaruizra/Geekbench5-data-analysis-tool#usage, you're mentioning some dependencies, including "json". 

That is actually useless, because json is a built-in python library. You don't have to install it, it's already there

**Comment by devlocalhost** [comment]
It is not even an existing library (pypi.org) it doesn't exist on pypi.org

```
ERROR: Could not find a version that satisfies the requirement json (from versions: none)
ERROR: No matching distribution found for json
```

**Comment by devlocalhost** [comment]
Another thing I noticed. You're importing (and also mentioning it as a "dependency") "requests.exceptions". That isn't needed either. "exceptions" is a part of "requests" which you are already importing

**Comment by jaruizra** [comment]
Hi, thanks for pointig that out, yeah, you only need to import those modules on python code, and not installed them. It makes no sense

I will update the usage file
